site_name: "Threat Hunt Labs"
site_url: "https://threathuntlabs.com"
site_description: "An independent repository for live cyber threat Hunting, intelligence, playbooks, and raw telemetry."
site_author: "Threathuntlabs Team"

# Ensure clean URLs (removes .html from links for better SEO)
use_directory_urls: true


theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

nav:
  - Home: index.md

  - Foundations:
      - 10 Common Mistakes: foundations/10-Common-Mistakes-Every-Beginner-Makes-When-Learning-Threat-Hunting.md
      - Cybersecurity Fundamentals: foundations/Cybersecurity-Fundamentals-The-Foundation-Every-Threat-Hunter-Needs-part-1.md
      - Why and Where Threat Hunting: foundations/Why-Every-Organization-Needs-Threat-Hunting.md
      - Threat Hunting Explained: foundations/Threat-Hunting-Explained-Beyond-Alerts-Dashboards-and-SIEM-Queries.md
      - Data Pipeline: foundations/Threat-Hunting-Data-Pipeline.md
      - Life Cycle: foundations/Inside-a-Threat-Hunt-Understanding-the-Threat-Hunting-Lifecycle.md
      - Types: foundations/Types-of-Threat-Hunting-Choosing-the-Right-Hunting-Strategy.md
      - Data Analysis Techniques: foundations/Threat-Hunting-Data-Analysis-Techniques.md
      - Hypothesis Development: foundations/Hypothesis-Development-Thinking-Like-a-Threat-Hunter-Before-Writing-a-Single-Query.md
      - Methodologies: foundations/Threat-Hunting-Methodologies-Choosing-the-Right-Hunting-Approach.md
      - Mindset: foundations/The-Threat-Hunting-Mindset-Thinking-Like-an-Attacker.md
      - Maturity Model: foundations/The-Threat-Hunting-Maturity-Model-Explained.md

  - Start Hunting:
      - Lab Setup: Start-Hunting/threat-hunting-lab.md
      - Reading Logs: Start-Hunting/Reading-Raw-Logs-Like-a-Threat-Hunter.md
      - Solo Hunter to Enterprise: Start-Hunting/threat-hunting-program-models.md
      - Reporting: Start-Hunting/threat-hunting-documentation.md
      - Telemetry & Logs to collect: Start-Hunting/threat-hunting-device-logs-telemetry-details.html
      
  - Blog: https://blog.threathuntlabs.com
  
  - Hunting Case Studies:
     - Solarwind Supply Chain Attack: case-studies/hunting-the-SolarWinds-supply-chain-attack.md

  - Resources: Downloads/threat-hunting-related-document-references.md

  - 🔥Learn Cyber Attacks: learn-known-cyber-attacks/index.html
      
  - 🎯Live Threat Intel: https://intel.threathuntlabs.com
