site_name: Threat Hunting Labs
site_url: https://threathuntlabs.com

theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - blog

nav:
  - Home: index.md

  - Foundations:
      - What is Threat Hunting: foundations/10 Common Mistakes Every Beginner Makes When Learning Threat Hunting.md

  - MITRE ATT&CK:
      - Introduction: mitre/introduction.md

  - Windows Hunting:
      - PowerShell Hunting: windows/powershell-hunting.md
