name: Deploy MkDocs
# Add this at the top level of your YAML file
permissions:
  contents: write
  pages: write
  id-token: write

# Add this to prevent multiple deployments from overlapping
concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install MkDocs
        run: |
          pip install mkdocs-material

      - name: Deploy
        run: |
          mkdocs gh-deploy --force
